version: '3.9'

services:
  backend:
    container_name: kyra-node-prod
    restart: always
    command: yarn start
    secrets:
      - env

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/production.dockerfile
    container_name: kyra-next-prod
    restart: always
    command: yarn start

secrets:
  env:
    name: "arn:aws:secretsmanager:eu-west-2:357483939706:secret:prod/kyra-full-stack/.env-6jruig"
    external: true