version: '3.9'

services:
  backend:
    build: ./backend
    image: kyra-node
    env_file: ./backend/.env
    ports:
      - '5000:5000'
  
  frontend:
    build: ./frontend
    image: kyra-next
    ports:
      - '5000:5000'
