version: '3.9'

services:
  backend:
    container_name: kyra-node-prod
    restart: always
    command: yarn start

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/production.dockerfile
    container_name: kyra-next-prod
    restart: always
    command: yarn start
