version: '3.9'

services:
  backend:
    container_name: kyra-node-dev
    restart: always
    command: yarn dev -L
    env_file: ./backend/.env
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/development.dockerfile
    container_name: kyra-next-dev
    restart: always
    command: yarn dev