version: '3.9'

services:
  backend:
    container_name: kyra-node-dev
    restart: always
    command: yarn dev -L

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/development.dockerfile
    container_name: kyra-next-dev
    restart: always
    command: yarn dev