version: '3.9'

services:
  backend:
    build: ./backend
    image: kyra-node
    env_file: ./backend/.env
  
  frontend:
    image: kyra-next
    ports:
      - '3000:3000'
    depends_on:
      - backend
