name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install root dependencies
        run: npm install
      - name: Add .env variables
        working-directory: ./backend
        env:
          FOURSQUARE_API_VERSION: v3
          FOURSQUARE_API_KEY: ${{ secrets.FOURSQUARE_API_KEY }}
          FOURSQUARE_CLIENT_SECRET: ${{ secrets.FOURSQUARE_CLIENT_SECRET }}
          FOURSQUARE_CLIENT_ID: ${{ secrets.FOURSQUARE_CLIENT_ID }}
        run: |
          touch .env
          echo FOURSQUARE_API_VERSION="${{ env.FOURSQUARE_API_VERSION }}" >> .env
          echo FOURSQUARE_API_KEY="${{ env.FOURSQUARE_API_KEY }}" >> .env
          echo FOURSQUARE_CLIENT_SECRET="${{ env.FOURSQUARE_CLIENT_SECRET }}" >> .env
          echo FOURSQUARE_CLIENT_ID="${{ env.FOURSQUARE_CLIENT_ID }}" >> .env
        shell: bash
      - name: Install backend dependencies
        working-directory: ./backend
        run: yarn install
      - name: Run tests
        working-directory: ./backend
        run: yarn test
